'##########################################################################
'
' screen utils
'
'##########################################################################

  declare sub Screen.Init
  declare sub Screen.Footer
  declare sub Screen.FooterYesNo
  declare sub Screen.HeaderUDLR(canUp%,canDown%)
  declare sub Screen.FooterInputOK
  declare function Screen.Field%(label$, value$, type$, rev%)
  declare sub Screen.Header(title$)
  declare sub Screen.H1(title$)
